// Deterministic draft builders for TicketGen page — CONTRACTS.md §6
// PURE functions: no side effects, fully unit-testable.

export interface PoStoryDraft {
  summary: string;
  description: string;
}

export interface DevTaskDraft {
  summary: string;
  description: string;
}

export interface TicketDraftPair {
  po: PoStoryDraft;
  dev: DevTaskDraft;
}

/**
 * Build a PO user story draft from a plain-English feature description.
 *
 * Produces:
 *  - summary: first sentence / line (≤ 255 chars)
 *  - description: "As a … I want … so that …" user-story scaffold + Given/When/Then ACs
 */
export function buildPoStory(
  featureDescription: string,
  storyPoints?: number
): PoStoryDraft {
  const trimmed = featureDescription.trim();

  // summary = first line, truncated to 255 chars
  const firstLine = trimmed.split("\n")[0].trim();
  const summary = firstLine.length <= 255 ? firstLine : firstLine.slice(0, 252) + "...";

  const pointsNote =
    storyPoints != null ? `\nEstimated story points: ${storyPoints}` : "";

  const description = `## User Story

As a user,
I want ${trimmed}
so that I can achieve my goal and the team delivers value.

${pointsNote ? pointsNote + "\n\n" : ""}## Acceptance Criteria

**Given** [a precondition / starting state]
**When** [the user performs an action]
**Then** [an observable outcome occurs]

**Given** [another scenario]
**When** [the user performs an action]
**Then** [another observable outcome]

## Additional Notes

${trimmed}

---
*Generated by InvokeBoard — review and edit before creating in Jira.*`;

  return { summary, description };
}

/**
 * Build a Dev task draft from a plain-English feature description.
 *
 * Produces:
 *  - summary: "Implement: <first line>"
 *  - description: technical checklist + implementation notes scaffold
 */
export function buildDevTask(
  featureDescription: string,
  technicalNotes?: string
): DevTaskDraft {
  const trimmed = featureDescription.trim();

  const firstLine = trimmed.split("\n")[0].trim();
  const rawSummary = `Implement: ${firstLine}`;
  const summary = rawSummary.length <= 255 ? rawSummary : rawSummary.slice(0, 252) + "...";

  const techSection = technicalNotes
    ? `## Technical Notes\n\n${technicalNotes.trim()}\n\n`
    : "";

  const description = `## Overview

${trimmed}

${techSection}## Implementation Checklist

- [ ] Understand requirements and clarify with PO if needed
- [ ] Design solution approach and update this ticket with decisions
- [ ] Implement feature / fix
- [ ] Write or update unit tests (target ≥ 80 % coverage on changed code)
- [ ] Write or update integration tests if applicable
- [ ] Update API documentation / OpenAPI spec if endpoints changed
- [ ] Self-review diff — check for debug logs, commented-out code, TODOs
- [ ] Open PR and link to this ticket + related PO story
- [ ] Address code review feedback
- [ ] Verify in staging/preview environment before merging

## Definition of Done

- All checklist items complete
- CI pipeline green (build, typecheck, test, lint)
- PR reviewed and approved
- Ticket status updated to Done

---
*Generated by InvokeBoard — review and edit before creating in Jira.*`;

  return { summary, description };
}

/**
 * Build a matched PO + Dev draft pair from a single description.
 */
export function buildDraftPair(
  featureDescription: string,
  storyPoints?: number,
  technicalNotes?: string
): TicketDraftPair {
  return {
    po: buildPoStory(featureDescription, storyPoints),
    dev: buildDevTask(featureDescription, technicalNotes),
  };
}
